###
#https://shifty200.github.io/CAB203_A1_Project_New/com.example.quizapp/module-summary.html#
###

name: Prototype Testing and Build

permissions:
  contents: write
on:
  push:
    branches: [ "prototype1" ]
  pull_request:
    branches: [ "prototype1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Run Tests
        run: mvn test
        

      - name: Publish Javadoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/javadoc
